### ISSUE TITLE
NekoEditor2D bugs

### ISSUE THREAD

**Issue by feltos** [EliasFarhan/NekoEngine#1]
Bugs Neko Editor

1) Si l’on veut mettre un point dans un valeur (par exemple 0.5 pour la scale) cela fait planter le programme si l’on utilise le point du pavé numérique. ERROR : vector subscript out of range.

![1](https://user-images.githubusercontent.com/23698291/65029348-dddd2180-d93d-11e9-954b-6ecdb3913859.PNG)

2) Si l’on crée une scène contenant une entité avec un spine animation, qu’on le load,qu’on sauve cette scène, qu’on crée une nouvelle scène et qu’on ouvre la scène contenant ce spine animation le programme se bloque. ERROR : Unhandled exception thrown : read access violation. Dans imgui.cpp, ligne 2321.

![2](https://user-images.githubusercontent.com/23698291/65029384-efbec480-d93d-11e9-8859-73fd7f4cae75.PNG)

3) Si l’on crée un spine animation, qu’on le load et qu’on affiche la preview celle-ci restera indéfiniment sur l’écran même si le component ou l’entité est supprimée. La seule manière de changer cela est d’afficher autre chose dans le viewer. 

![3](https://user-images.githubusercontent.com/23698291/65029401-f8af9600-d93d-11e9-900d-74cac58b41cc.PNG)

4) Si l’on veut sauver une scène et que l’on clique dans le dossier scène sur une scène déjà existante (pour prendre le même nom ou par erreur) le programme plante instantanément. ERROR : L”Buffer is too small” && 0.

![4](https://user-images.githubusercontent.com/23698291/65029413-fe0ce080-d93d-11e9-8d9c-abbeed073c67.PNG)

5) Il est impossible de supprimer un collider, peu importe le type du collider.

![5](https://user-images.githubusercontent.com/23698291/65029420-036a2b00-d93e-11e9-86bd-01650a49b86a.PNG)

**Comment by EliasFarhan** [comment]
Everything has been corrected, please do report issues separately
