### ISSUE TITLE
#include <filesystem> compilation error

### ISSUE THREAD

**Issue by LoshkinOleg** [EliasFarhan/NekoEngine#2]
En essayant de lancer "bench_algo | Debug", cet include n'est pas reconnu.
- Je suis sur Ubuntu 18.04.4 LTS
- Je suis sur CLion 192.6015.37
- J'ai installé OpenGL avec GLUT (http://www.codebind.com/linux-tutorials/install-opengl-ubuntu-linux/)
- J'ai installé VulkanSDK en téléchargeant le dernier tarball sur le site officiel
- J'ai installé clang-9 avec la commande automatique suggérée sur https://apt.llvm.org/
- J'a mis clang-9 en compilateur C
- J'ai mis clang++-9 en compilateur C++

L'erreur provient du fait que "filesystem" est apparament sous "experimental/filesystem" ce qui me mène à penser que je n'ai pas le bon standard c++ malgré la génération correcte par CMake qui est sensé enforcer le standard 17?

**Comment by LoshkinOleg** [comment]
Solved:

C'est la version Ubuntu 18.04.4 LTS qui posait problème. Cette version n'a pas la dernière version de la librairie C. Donc il faut installer la dernière version d'Ubuntu!

**Comment by EliasFarhan** [comment]
Pour l'explication un peu plus poussé, c'est la libstdc++ qui est lié avec la version du compilateur Gnu Compiler Collection (GCC) de base qui pose problème vu que <filesystem> était en expérimental et doit être lié à la main (en ajoutant -lstdc++fs). Là, vous me dites, mais j'utilise clang-9, bah en fait clang-9 link aussi la libstdc++ de base du système, donc soit le cmake check tous les compilateurs et met les bons flags, soit je mets Ubuntu 19.10 comme minimun requirements.
