### ISSUE TITLE
Test input

### ISSUE THREAD

**Issue by EthanCavadia** [EliasFarhan/NekoEngine#20]
J'ai commencé à intégré les inputs de SDL dans les fichiers sdl_input, mais je ne sais pas ou l'intégré pour pouvoir le tester.

**Comment by EliasFarhan** [comment]
Si tu les intègres dans le sdl_engine, tu peux les utiliser dans Neko_TEST après.
Quitte à faire une nouvelle exécutable comme comp_graph juste pour tester les inputs pour l'instant.
