### ISSUE TITLE
fmod cmakelist error 

### ISSUE THREAD

**Issue by AdamNaji** [EliasFarhan/NekoEngine#21]
j'ai un problème lors de l’intégration de fmod : 

voici le contenu de ma cmakelist : 

`cmake_minimum_required(VERSION 3.10)

file(GLOB_RECURSE target "include/*.h" "src/*.cpp")

add_executable(fmod ${target})

include_directories(NekoEngine/externals/Fmod-2.00.08/api/core/inc /api/studio/inc )

link_directories("NekoEngine/externals/Fmod-2.00.08/api/core/lib" "/api/studio/lib")

target_link_libraries(${target}
    "/api/core/lib/x86/libfmodL.so"
    "/api/core/lib/x86/libfmod.so")`

voici l'erreur sortie par cmake : 

CMake Error at CMakeLists.txt:11 (target_link_libraries):
  Cannot specify link libraries for target "/api/core/lib/x86/libfmodL.so"
  which is not built by this project.

**Comment by EliasFarhan** [comment]
target_link_libraries ne prend pas un chemin en entrée, tu dois donner un chemin dans link_directories(), puis ensuite ajouter target_link_libraries(${target} libfmod libfmodL) ou quelque chose du genre.

Les .so sont pour Linux exclusivement aussi donc faut pas oublier d'ajouter le if(UNIX)
