### ISSUE TITLE
Suggestion: ségmenter d'avantage matrix.h [Oleg].

### ISSUE THREAD

**Issue by LoshkinOleg** [EliasFarhan/NekoEngine#25]
Je suis revenu sur la branche sprint1_transform et on a beaucoup de mal à se retrouver dans le header matrix.h .
Je propose qu'on le ségmente d'avantage:
- matrix.h contenant toutes les déclarations + usings
- matrix.cpp contenant les implémentations des fonctions relatives aux matrices.
- transform.cpp contenant les implémentations des fonctions relatives aux Transform-Model-Matrix.

Comme ça, pour utiliser n'importe quelle fonctionalité d'une matrix on a qu'à include matrix.h?

**Comment by EliasFarhan** [comment]
Ok, mais les Intrinsics doivent rester dans le header pour que le compilateur puisse inliner le code et optimiser pour ce qu'il a besoin.

**Comment by LoshkinOleg** [comment]
Humm ouais alors j'avais pas pensé à ça effectivement...
Par contre du coup faut que je déplace les bodys de mes fonctions de Transform3d qui sont dans transform.h dans matrix.h aussi du coup vu que j'ai des fonctions inlinées dedans?

**Comment by EliasFarhan** [comment]
En fait, tu peuxx faire un autre header et c'est bon aussi.
