### ISSUE TITLE
Erreur de Synthaxe, custom_allocator.h

### ISSUE THREAD

**Issue by SebastienFeser** [EliasFarhan/NekoEngine#29]
Hello, j'ai essayé de compiler Neko_TEST, mais il m'arrête parce qu'il me dit qu'il y a une erreur de syntaxe dans le custom_allocator.h à la ligne 233.

Voilà ce qu'il y a à cette ligne:
´´´
neko_assert(allocatedSize == sizeof(T) and alignment == alignof(T), "Pool Allocator can only allocate one Object pooled at once");
´´´
Et la Description de l'erreur: "erreur de synthaxe : absence de ')' avant l'identificateur 'and'
et pour la même ligne
"erreur de syntaxe: absence de ';' avant '{'

Est-ce que qqn aurait une idée de ce que le problème peut être?

**Comment by EliasFarhan** [comment]
MSVC aime pas le mot-clé "and". Je viens de corriger et pusher.
