### ISSUE TITLE
msvcptrd.lib et libcptmtd.lib double définition

### ISSUE THREAD

**Issue by FloreauLuca** [EliasFarhan/NekoEngine#3]
Quand j'essaye de lancer le Neko_TEST, les erreurs suivantes apparaissent :
https://pastebin.com/afstuS8P

Je suis sur Windows 10, Visual Studio 2019 16.4.4 et j'utilise CMake 3.16.4.

![bug1](https://user-images.githubusercontent.com/43808018/74029413-f3b2b800-49ac-11ea-9bc6-4ffe2dce076f.png)

**Comment by FloreauLuca** [comment]
Solution trouvée : 
Les projets gtest et gtest_main doivent avoir la même bibliothèqe runtime que les autres projets, c'est-à-dire "DLL débogage multithread".
Pour les modifié il faut aller dans Projets\Propriété\C/C++\Génération de code\Bibliothèque Runtime

![debug1](https://user-images.githubusercontent.com/43808018/74030584-b3a10480-49af-11ea-86b3-6b5c952827bb.png)

Pour plus d'info : https://stackoverflow.com/questions/14714877/mismatch-detected-for-runtimelibrary

**Comment by EliasFarhan** [comment]
La problème avec ta solution est que tu dois faire ça à chaque fois que tu lances CMake. Je viens modifier le CMakeLists.txt pour effectuer le changement automatiquement sur develop pour MSVC.
