### ISSUE TITLE
Optimisation Quaternions

### ISSUE THREAD

**Issue by SebastienFeser** [EliasFarhan/NekoEngine#32]
Hello,

Je n'ai pas beaucoup d'idée de quelles optimisations je pourrais intégrer pour les Quaternions et surtout sachant que le jeu va être un Minecraft like, qu'est-ce qui serait le plus judicieux à faire. 
Est-ce que qqn aurait des idées?

**Comment by LoshkinOleg** [comment]
Bah déja comment les quaternions seront utilisés en moyenne?
Quelles fonctions vont être importantes?
Combien de temps prennent-elles?
Code source de ces fonctions?
