### ISSUE TITLE
Inverser la logique de neko_assert [Oleg]?

### ISSUE THREAD

**Issue by LoshkinOleg** [EliasFarhan/NekoEngine#36]
J'ai passé 10 minutes à essayer de debugger qqch en pensant que la logique du neko_assert() était inversée.
Vous voulez pas l'inverser de base pour que neko_assert(CONDITION) se comporte comme un EXPECT_TRUE(CONDITION)?

Voilà le bout de code qui m'avait bloqué:
```
neko_assert(Contains(key), "neko::Map<Key,Value>::Append(const Key, const Value): Map already contains Key passed.");

qui devient:
neko_assert(!Contains(key), "neko::Map<Key,Value>::Append(const Key, const Value): Map already contains Key passed.");
```

Actuellement l'assert se comporte comme un EXPECT_FALSE...

**Comment by EliasFarhan** [comment]
Non, un assert doit être true pour passer. Si la condition est 0/false,
l'assert fait abort, c'est le standard pour les assert.
