### ISSUE TITLE
Questions maps (SmallDynamicMap & heritage)

### ISSUE THREAD

**Issue by SebastienFeser** [EliasFarhan/NekoEngine#38]
Hello, nous avions deux questions à propos des maps.

Premièrement, nous avons créé 4 types de maps différents:
- **FixedMap** (taille fixe, mémoire heap (on utilise du coup std::vector))
- **SmallFixedMap** (taille fixe, mémoire stack (on utilise du coup std::array))
- **DynamicMap** (taille dynamique, mémoire heap (on utilise du coup std::vector))
- **SmallDynamicMap** (taille dynamique, mémoire stack (on utilise du coup std::array))

**Question 1:**
Nous avons du coup rencontré des problèmes avec la SmallDynamicMap étant donné que pour celle-ci, on utilise un std::array qui lui, a une taille fixe. La question est de savoir, si ce type de map est réellement utile et si oui, qu'est-ce qui pourrait être plus judicieux de faire à la place de clear et de recréer l'array à chaque fois qu'on y modifie quelque chose?

**Question 2:**
Sinon, nous nous sommes également posés la question de si on ne devrait pas faire un parent de ces classes, étant donné qu'elles sont similaires. Est-ce que dans ce cas précis, les classes sont intrinsèquement différentes?

**Comment by EliasFarhan** [comment]
Vous avez pas besoin de faire SmallDynamicMap.
