### ISSUE TITLE
Arrêt de "cmd.exe"

### ISSUE THREAD

**Issue by EthanCavadia** [EliasFarhan/NekoEngine#4]
Quand je build le Neko_TEST j'ai cette erreur :
Je suis sur Windows 10, Visual Studio 2019 16.4.4 et j'utilise CMake 3.16.4.
 
![cmd exe_error](https://user-images.githubusercontent.com/43807406/74089301-12de4200-4aa0-11ea-9804-111c9c9b3e59.png)

J'ai essayé de désactiver mon anti-virus mais sa n'a rien changé.

**Comment by EliasFarhan** [comment]
Ok, l'erreur m'aide pas beaucoup, est-ce que t'arrives à montrer la sortie de la compilation.
cmd.exe, c'est le terminal Windows, donc il y a quelque chose au niveau des commandes CMake de fichiers qu'il a pas réussi à faire. T'as bien python3 d'installer sur l'ordi?

**Comment by EthanCavadia** [comment]
C'était simplement sa, j'avais oublier de le réinstaller.

**Comment by EliasFarhan** [comment]
Je corrige le data.cmake qui devrait te forcer à installer Python 3 avant que tu ouvres Visual Studio 2019.
