### ISSUE TITLE
Impossible d'installer VS2019 [Oleg].

### ISSUE THREAD

**Issue by LoshkinOleg** [EliasFarhan/NekoEngine#40]
Quand j'ouvre le Visual Studio Installer, d'habitude on est sensé avoir un onglet pour installer toutes les releases actives de VS, dont VS2019.
Je n'ai pas cet onglet et je n'arrive donc pas à l'installer. La dernière version qu'il me propose est la VS 2017.

J'ai essayé de completement supprimer tous mes fichers (je pense tous) Visual Studio et re-installer tout depuis https://visualstudio.microsoft.com/vs/ mais il m'enmène à la page de download du installer Community qui ne veut pas me montrer de version 2019...

Si qqn a des idées à quoi c'est dû, ce serait le bienvenu pcq là je n'ai pas moyen de tester quoi que ce soit sur Visual Studio 2019 du coup...

![vs2019](https://user-images.githubusercontent.com/43808200/76831075-e9df6880-6826-11ea-83dc-ca4bf1286fbe.png)

**Comment by EliasFarhan** [comment]
Je suis pas sûr que c'est quelque chose à voir avec le Neko Engine ;)

**Comment by LoshkinOleg** [comment]
Bah si, faut bien que je teste que mon code de Neko fonctionne sur Visual Studio 2019 que bcp de gens utilisent comme l'erreur que Séb avait quand je mettais des array flexibles en membres de classes ou le const size_t len = state.range(0) qui passait sur clang et pas sur msvc ;)

**Comment by EliasFarhan** [comment]
Oui, mais je suis pas Microsoft, donc je peux pas vraiment t'aider pour ça
aussi...

**Comment by CanasSimon** [comment]
Ton installer a la mauvaise version
Tu es à la 1.18.1104.625 (en bas à droite) alors que la version actuelle est 2.5.2057.204

Please try update first

**Comment by LoshkinOleg** [comment]
Simon? Je te dois la vie.
