### ISSUE TITLE
Peut pas include file_utility

### ISSUE THREAD

**Issue by CanasSimon** [EliasFarhan/NekoEngine#43]
Pour une certaine raison, je ne peut plus include file_utility. A chaque fois que j'essayer, le compilateur me retourne une erreur de ce type:
```
unresolved external symbol "class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const __cdecl neko::LoadFile(class std::basic_string_view<char,struct std::char_traits<char> > const &)" (?LoadFile@neko@@YA?BV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@AEBV?$basic_string_view@DU?$char_traits@D@std@@@3@@Z)	
```

Je ne sais pas pourquoi ce fichier en particulier

**Comment by EliasFarhan** [comment]
T'as checké que le prototype de LoadFile correspond à la définition de
LoadFile dans le fichier source?

**Comment by CanasSimon** [comment]
Ah.... c'était ça.... le prototype prenait en argument un string_view alors que le cpp prennais un string basique...
