### ISSUE TITLE
Que pourrais-je faire comme optimisation pour les Quaternions?

### ISSUE THREAD

**Issue by SebastienFeser** [EliasFarhan/NekoEngine#45]
Hello,
J'ai pas trop d'idées de ce que je pourrai faire comme optimisation éventuelle pour les Quaternions. Est-ce que tu aurais éventuellement une piste de ce que je pourrais faire?

**Comment by LoshkinOleg** [comment]
Benchmarks pour commencer. Bench tout et envoie le résultat ici?

**Comment by EliasFarhan** [comment]
Comme dit Oleg, dans quel cas est utilisé le Quaternion, quels sont les opérations qui sont effectuées, combien de temps prennent-elles? Est-ce que tu peux transposer les données pour avoir du SoA (Structures of Array)?
