### ISSUE TITLE
Une piste pour se renseigner sur les Signals dans le Multithreading [Oleg] ?

### ISSUE THREAD

**Issue by LoshkinOleg** [EliasFarhan/NekoEngine#46]
@EliasFarhan , je ne trouve pas la présentation d'Ubisoft dont tu avais parlé en cours sur le sujet.

J'ai brièvement regardé ce qui ressort quand on fais des recherches sur "signal multithreading" sur google et je tombe sur les systèmes de signals de Linux et sur les systèmes de signals qui sont retournés quand on fais des conneries dans le code (genre division par 0).

Est-ce que c'est bien des signals de l'OS que tu voulais que je parle?

**Comment by EliasFarhan** [comment]
Pas de soucis, j'ai retrouvé le talk cppcon d'Ubisoft:
https://www.youtube.com/watch?v=X1T3IQ4N-3g
Il ne parle pas exactement de signals, mais tu peux résumer ce talk dans ta
présentation pour dans deux semaines.

**Comment by LoshkinOleg** [comment]
Oki parfait, merci!

**Comment by LoshkinOleg** [comment]
Du coup ce talk est surtout sur le sujet des atomics.
Donc est-ce que tu voulais que je présente plus en profondeur la partie à 8:30 ou il parle d'events pour réveiller des threads / les faire attendre ou est-ce que je parle de tout le talk, donc en mettant l'accent sur les atomics?

Partie dont je parle: https://youtu.be/X1T3IQ4N-3g?t=508

**Comment by EliasFarhan** [comment]
À ta discrétion, mais pourquoi pas.
