### ISSUE TITLE
problème configure cmake fmod

### ISSUE THREAD

**Issue by AdamNaji** [EliasFarhan/NekoEngine#47]
lorsque j'essaye de configure avec cmake , j ai une erreur dans la cmakelist 
voici l'erreur :
```
 CMake Error at CMakeLists.txt:118 (add_subdirectory):
  add_subdirectory given source "fmod/" which is not an existing directory.
```

voici les ligne de la cmakelist : 
```
if(Neko_Fmod)
add_subdirectory("${EXTERNAL_DIR}/Fmod-2.00.08")
set(Fmod_VERSION 2.00.08)
set(Fmod_DIR $(EXTERNAL_DIR, Fmod(Fmod_VERSION)/))
add_subdirectory("fmod/")
```

**Comment by EliasFarhan** [comment]
add_subdirectory("common/fmod/")? je peux pas deviner si je ne sais pas où
t'as mis ton dossier fmod...

**Comment by AdamNaji** [comment]
effectivement j 'avais pas mis ou étais le dossier , le problème est régler
