### ISSUE TITLE
Nomenclature des custom containers [Oleg] ?

### ISSUE THREAD

**Issue by LoshkinOleg** [EliasFarhan/NekoEngine#49]
Je propose qu'on mette en place une nomenclature cohérente pour les custom containers.

Pour l'instant je partais sur le coding style usuel de Neko avec les exceptions suivantes:
- Les fonctions qui ont une correspondance directe dans la lib standard suivent la meme nomenclature que la lib standard. (ex: insert() et non pas Insert(), push_back() et non pas PushBack() )
- Les types qui ont une correspondance directe dans la lib standard suivent la meme nomenclature que la lib standard. (ex: class iterator et non pas class Iterator )

J'ai vu que Guillaume mettait DynArray alors que Séb et moi mettions DynamicMap.

Je propose donc la nomenclature suivante pour les custom containers:
- Le coding style de Neko s'applique sauf pour les classes / fonctions qui ont une correspondance directe dans la lib standard.
- Les noms des classes / methodes ne contiennent pas d'abbréviations.

Au passage je rappele que les fichiers des custom containers doivent être rangés dans:
- Pour les .h: core/include/utilities
- Pour les .cpp: core/src/utilities

Dites moi ce que vous en pensez!

**Comment by EliasFarhan** [comment]
Je veux pas casser le coding style Neko, même pour les custom containers (ils ne sont pas une extension de la STL, mais des containers propres à nos custom allocators). 
Par contre, lorsque cela fait du sens, il faut préférer les noms de la STL (en gardant le coding style Neko).
Sinon je suis d'accord avec le fait d'éviter les abbrévations dans les noms de classes.
Pour l'emplacement des fichers, c'est faux. J'ai dit en cours de mettre dans un nouveau dossier (core/include/custom_container et core/src/custom_container), mais ne mettez pas des noms avec custom (pas de custom_container/custom_map.h, juste custom_container/map.h)

**Comment by LoshkinOleg** [comment]
Oki pour les noms.

Et ouais effectivement pour les noms de dossiers, j'ai confondu pcq qqn avait mis les siens dedans, my bad.

Oki pour résumer:
- Le coding style est respecté dans tous les cas.
- Il est preferable de donner des noms similaires à ceux présent dans la lib standard pour les noms des methodes / classes en les adaptant au coding style de Neko (ex: FixedMap::Iterator ou FixedMap::Insert() )
- Eviter de mettre des abréviations dans les noms des classes / methodes.
- Mettre les fichiers des custom containers dans **core/include/custom_container** et **core/src/custom_container** pour les **.h** et **.cpp respectivement**.
- Ne pas mettre de "custom" dans les noms de fichiers .h et .cpp des custom containers.

Voilà, dites-moi si c'est bon comme ça!
