### ISSUE TITLE
Developer le projet sur Ubuntu en dual boot [Tuto]

### ISSUE THREAD

**Issue by LoshkinOleg** [EliasFarhan/NekoEngine#5]
Avant de commençer vous avez besoin de:
- Clé USB 4gb mini
- Rufus: https://rufus.ie/
- Dernière version non LTS d'Ubuntu (19.10), les anciennes n'ont pas la bonne libc

Allez dans les BIOS de votre PC:
- Désactivez le Fast Boot, le Secure Boot et CSM si ils sont présents.
- Configurez le hardware pour utiliser le profil performance si possible.

Ensuite montez l'ISO d'Ubuntu sur la clé USB en utilisant Rufus:
- Séléctionnez l'ISO et l'USB
- Quand un message popup vous demande si vous voulez une version ISO ou DD, séléctionnez DD.

Installer et mettre à jour Ubuntu:
- Insérez la clé avec Ubuntu et bootez la.
- Dans les options d'installation, checkez la case "Install all third-party software..." et je conseille d'installer la version "Minimal install".
- Une fois dans Ubuntu, lancez le Software & Update et dans les settings cochez le téléchargement de tout software third-party.
- Fermez la fenêtre et cliquez sur "Install Now" puis une fois les mises-à-jour terminées, "Restart Now"

Installer les dépendances:
Allez dans le Software Store et installez CLion
Allez dans le terminal et lançez:
- sudo apt-get update
- pour git, opengl, opengles: sudo apt-get install libglu1-mesa-dev freeglut3-dev mesa-common-dev git libglfw3-dev libgles2-mesa-dev
- pour clang: sudo bash -c "$(wget -O - https://apt.llvm.org/llvm.sh)"

Pour VulkanSDK:
- Allez ici: https://vulkan.lunarg.com/sdk/home#linux
- Et téléchargez le "Latest SDK Tarball"
- Extrayez-le qqpart puis allez dans <dossierDeDestination>/1.2.131.2/x86_64/bin
- Ouvrez le terminal et entrez "pwd" pour avoir le full path vers ce dossier.
- Copiez le path
- Puis entrez: sudo nano /etc/environment
- Dans l'éditeur qui s'est ouvert, paste le path vers les binaires de Vulkan à la fin de la string après avoir rajouté un ":" comme pour tout le reste. (ex: <lastEntryInPATH>:/home/user/Desktop/VulkanSDK/1.2.131.2/x86_64/bin)
- Write out (Ctrl+O), Exit (Ctrl+X)
- Redémarrez ou log out - log in
- Pour vérifier que le PATH est set, ouvrez le terminal et entrez: echo $PATH.  La sortie doit être à peu prêt comme ça: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/home/user/Desktop/VulkanSDK/1.2.131.2/x86_64/bin:/snap/bin

Après avoir clone le projet:
- Lancez CLion et ouvrez le projet en séléctionant "Open" et en séléctionant le dossier NekoEngine
- Allez dans File->Settings->Toolchain
- Dans le field c compiler, rajouter clang-9: /usr/bin/clang-9
- Dans le field c++ compiler, rajouter clang++-9: /usr/bin/clang++-9
- Allez dans File->Settings->Editor->Code Style ->C/C++: clickez sur l'icone de l'engrenage->Import Scheme->IntelliJ .... XML.   Selectionnez NekoEngine/doc/neko_style.xml et checkez la box "Current scheme"

Rajouter un build Release:
- Allez dans File->Settings->Build,Exectution,Deployement->CMake
- Clickez sur le petit plus pour rajouter automatiquement un build Release

Si qqch ne marche pas:
- Priez.

**Comment by EliasFarhan** [comment]
Tu peux faire une entrée sur le wiki quand t'auras fini de remplir ce tutoriel.

Tu peux installer le Vulkan SDK depuis apt-get glslang-dev, ce qui est un peu plus pratique que bidouiller le path d'environnement ;)

J'utilise le clang classique du apt aussi.

**Comment by LoshkinOleg** [comment]
@EliasFarhan C'est fait!
