### ISSUE TITLE
Suggestion: Nomenclature des TESTs [Oleg].

### ISSUE THREAD

**Issue by LoshkinOleg** [EliasFarhan/NekoEngine#50]
Le fichier test_mathematics.cpp comporte actuellement 3 tests différents: 1 pour la neko::FuncTable, 1 pour neko::Quaternion et 1 pour neko::Mat4f.

Je propose donc:
- Qu'on les sépare dans des fichiers test_functable.cpp, test_quaternion.cpp et test_matrix.cpp
- Qu'on renomme le 1er argument de ces TESTs de "Engine" à "Mathematics" ou encore plus précisément "FuncTable", "Quaternion" et "Matrix".

Dites-moi ce que vous en pensez!

**Comment by EliasFarhan** [comment]
Tout à fait d'accord

**Comment by LoshkinOleg** [comment]
Oki, j'ai déplacé les tests de functable et de mat4f. J'att la réponse de Séb pour bouger les tests de quaternions.
Les changements seront sur sprint3_map.
