### ISSUE TITLE
problème utilisation des string_views

### ISSUE THREAD

**Issue by SebastienFeser** [EliasFarhan/NekoEngine#52]
Hello,
Je n'arrive pas à utiliser les stringviews.

J'ai commencé par include string_view dans le fichier, mais quand je fais std::string_view ou que j'essaye d'accéder à n'importe quel membre similaire, rien ne m'est proposé et ça me met "namespace "std" n'a pas de membre "string_view""

Est-ce que quelqu'un pourrait éventuellement m'éclairer? Est-ce que vous auriez besoin d'informations supplémentaires?

**Comment by EliasFarhan** [comment]
Si j'ai pas le fichier, l'IDE que t'utilises, ce que t'essaies de faire
avec ton std::string_view, je ne peux pas t'aider.

**Comment by SebastienFeser** [comment]
J'utilise Visual Studio 19. Je suis dans un header et je l'utilise comme ça:
![image](https://user-images.githubusercontent.com/43807464/77526454-df5a4a00-6e8a-11ea-92e8-7283df9c5270.png)

**Comment by EliasFarhan** [comment]
Pourquoi t'as une variable globale string?

**Comment by SebastienFeser** [comment]
C'est juste pour tester les stringviews

**Comment by EliasFarhan** [comment]
Oui, mais on utilise les string_view généralement comme argument d'une
fonction, pas comme une variable...

**Comment by SebastienFeser** [comment]
C'est ce que j'ai fait, mais ça ne marche quand même pas. En gros ça me dit que les string_view n'existent pas. Du coup c'est le même problème

**Comment by SebastienFeser** [comment]
J'ai trouvé du coup quel était mon problème. J'essayais d'utiliser les string_views en dehors du projet
