### ISSUE TITLE
Unknown file error avec free()

### ISSUE THREAD

**Issue by StephenGrosjean** [EliasFarhan/NekoEngine#53]
Lorsque j'utilise free() voici l'erreur que j'obtient:
`
unknown file: error: SEH exception with code 0xc0000005 thrown in the test body.
`

```cpp
 size_t memorySize = 1024;
 void* data = malloc(memorySize);
 neko::FreeListAllocator allocator = neko::FreeListAllocator(memorySize, data);
 String str1 = String(allocator, "TEST");
 free(data);
```

**Comment by EliasFarhan** [comment]
Active le Neko_Assert dans le cmake pour checker que tu ne fais pas
n'importe quoi avec les custom_allocators.
Parce que ca sent la corruption de mémoire.

**Comment by StephenGrosjean** [comment]
Neko_Assert est deja activé

En debug j'ai une violation d'accès en écriture dans custom_allocator.cpp L146:
```cpp
freeBlock = freeBlock->next;
```

**Comment by EliasFarhan** [comment]
Tu peux lancer le Neko_Test dans son entièreté, pas juste le Test que tu as
fait?

**Comment by StephenGrosjean** [comment]
Oui, 
J'obtient exactement le même résultat
![ErrorNeko](https://user-images.githubusercontent.com/40411159/77689652-520a1900-6fa2-11ea-8c6b-9c9d752ab54e.PNG)

**Comment by EliasFarhan** [comment]
T'as mis quoi comme alignement pour ton allocation?

**Comment by StephenGrosjean** [comment]
alignof(char)

**Comment by EliasFarhan** [comment]
Est-ce que tu peux tester la longueur de chaque allocation que tu fais?

**Comment by StephenGrosjean** [comment]
C'est a dire la longueur ?

**Comment by EliasFarhan** [comment]
Quand tu fais allocate, combien de bytes tu alloues à chaque fois ?

**Comment by StephenGrosjean** [comment]
8 bytes logiquement

**Comment by EliasFarhan** [comment]
Je m'en fous de la logique, je veux des données.

**Comment by StephenGrosjean** [comment]
TestString
```cpp
size_t memorySize = 1024;
size_t memorySize = 1024;
    void* data = malloc(memorySize);
    neko::FreeListAllocator allocator = neko::FreeListAllocator(memorySize, data);

    String str1 = String(allocator, "A");
```


CPP
```cpp
buffer_ = static_cast<char*>(allocator_.Allocate(
	            sizeof(char) * str.size()+1,
	            alignof(char)));
```
sizeof(buffer_) = 8

**Comment by EliasFarhan** [comment]
Mec, sizeof te donne la taille du pointeur buffer_, pas ce qu'il y a
dedans...
Tu peux print les str.size()?

**Comment by EliasFarhan** [comment]
Est-ce que tu peux pusher tes tests que je puisse checker ça de mon côté?

**Comment by StephenGrosjean** [comment]
J'ai fait un push sur la branche sprint3_string

**Comment by EliasFarhan** [comment]
Ok, j'arrive pas reproduire ton bug ni sur Linux, ni sur Windows sur VS2019. Supprime ton dossier Build et reconstruit ta solution CMake. C'est probablement une connerie de VS plus qu'autre chose.

Accessoirement, je t'ai mergé develop et corrigé deux trois trucs.

**Comment by StephenGrosjean** [comment]
J'ai supprimé le dossier build, et tout régénéré.
Le bug est toujours présent.

**Comment by EliasFarhan** [comment]
Tu peux lancer l'executable Neko_Test.exe en dehors de VS2019?

**Comment by StephenGrosjean** [comment]
Il plante aussi

**Comment by EliasFarhan** [comment]
T'as mis à jour ta version de Visual Studio 2019?
J'arrive pas à reproduire le bug sur ta branche... sur deux ordis
différents avec trois systèmes différents.

**Comment by StephenGrosjean** [comment]
J'ai mis a jour VS et Windows au cas ou.
Et toujours les mêmes erreurs.

sur la branche que j'avais push hier le free(data) était en commentaire, es-ce que tu la bien remis ?

**Comment by EliasFarhan** [comment]
La prochaine fois, t'apprendras à laisser les bugs quand je veux tester ton
code...
Non, je n'ai pas enlevé le commentaire, donc oui ca marchait chez moi
évidemment...

**Comment by EliasFarhan** [comment]
En checkant ton test, il faut faire les destructions dans cet ordre:

   1. Détruire les strings que tu as créé
   2. Détruire l'allocator
   3. Free data

Tu les fais dans cet ordre:

   1. Free data
   2. Random détruire les strings et l'allocator en sortant du scope.

Tu mếtonnes que ça marche pas bien.

**Comment by StephenGrosjean** [comment]
Ah, je comprend mieux.
Question: Comment je destroy le string? et comment je destroy l'allocator?

**Comment by EliasFarhan** [comment]
En mettant des accolades... Comme n'importe quelle variable locale.

**Comment by StephenGrosjean** [comment]
Le test fonctionne, c'est bien ça que tu voulais dire ?
```cpp
 size_t memorySize = 1024;
    void* data = malloc(memorySize);
    FreeListAllocator allocator = FreeListAllocator(memorySize, data);
    {
        String str1 = String(allocator, "A");
        String str2 = String(allocator, "B");
        String str3 = String(allocator, "A");
        String str4 = String(allocator, "D");

        EXPECT_TRUE(str1 == "A");
        EXPECT_TRUE(str1 != "Z");
        EXPECT_TRUE(str1 == str3);
        EXPECT_TRUE(str1 != str4);

        str1 += str2;
        String str5 = String(allocator, "TEST");
        str5 = "";
        str5 += str3;
        str5 += str2;

        EXPECT_TRUE(str1 == "AB");
        EXPECT_TRUE(str5 == str1);
    }
    allocator.~FreeListAllocator();
    free(data);
```

**Comment by EliasFarhan** [comment]
Yep, par contre c'est vraiment dég d'appeler le destructeur de l'allocator à la main comme ça. C'est pas grave si tu free data avant la destruction del'allocator, l'important c'est de faire les Deallocate avant.

**Comment by StephenGrosjean** [comment]
Yes, je l'ai laissé ce détruire tout seul. Tout fonctionne, merci.
