### ISSUE TITLE
UTF-8 

### ISSUE THREAD

**Issue by StephenGrosjean** [EliasFarhan/NekoEngine#55]
Je voulais savoir si ma manière de procéder pour l'UTF-8 était correct.

- On a un neko::String("âÂ Čšđ ě €€") avec des caractères unicode.

- On check pour chaque charactère si il est contenu dans la liste des caractères unicode.

- On remplace le caractère par son code (Ex: "\u20AC")

**Comment by EliasFarhan** [comment]
Difficile à dire comme ça. Essaie voir d'écrire ta String dans un fichier
et tu verras si t'as toujours les caractères unicodes.

**Comment by StephenGrosjean** [comment]
J'ai fait le test, pas tout les caractères sont transcrits.
âÂ Čšđ ě €€
âÂ ?š? ? €€

Donc es-ce que c'est une bonne idée de faire une table des caractères unicode et de les comparer à chaque fois?

**Comment by EliasFarhan** [comment]
Lire un fichier UTF-8 est probablement plus important/intéressant qu'écrire
dans un fichier.
