### ISSUE TITLE
Intrinsèques Quaternions

### ISSUE THREAD

**Issue by SebastienFeser** [EliasFarhan/NekoEngine#56]
Hello, je voulais avoir du feedback sur comment je pensais intégrer les intrinsèques pour les Quaternions.

Mon idée était de créer un FourQuaternion qui stocke 4 arrays (x,y,z,w) de 4 floats et ensuite de créer les fonctions intrinsèques.

Je pensais aussi créer un convertisseur d'un array ou vector de Quaternions en FourQuaternions.

Est-ce que l'idée est correcte? Est-ce que je devrais prendre d'autres choses en considération?

**Comment by EliasFarhan** [comment]
C'est pas une mauvaise, tu peux regarder les FourVec4f pour t'inspirer.

**Comment by SebastienFeser** [comment]
J'ai fait un schéma de comment je pensais implémenter le tout pour vraiment être sûr d'avoir tout compris. Est-ce que l'utilisation de mes quaternions va bien se faire comme ça?
![AoSoAQuaternions](https://user-images.githubusercontent.com/43807464/78244338-ab63d200-74e5-11ea-814f-d7dae966204d.png)
