### ISSUE TITLE
FourQuaternion AngleAxis array de radian_t ou de float

### ISSUE THREAD

**Issue by SebastienFeser** [EliasFarhan/NekoEngine#58]
Hello, j'ai implémenté la fonction Angle Axis qui prend de base en argument des radian_t.

Dans les FourQuaternions, je me demandais si je devais convertir directement dans la fonction les radian_t en float ou si je dois mettre en argument de la fonction des floats.

Si je convertis dans la fonction des radians_t en float, je vais devoir recréer un array<float, 4> du coup pas sûr que ce soit la meilleur des choses à faire.

Donc array<radian_t, 4> ou array<float, 4> en argument de la fonction AngleAxis?

**Comment by EliasFarhan** [comment]
Normalement je dirai array<radian_t, 4> pour rester cohérent, mais le
problème sera de loader la valeur correct si tu fais des intrinsics.
Donc je dirai en argument array<radian_t, 4>, mais tu stockes array<float,
4> dans FourQuaternions.
