### ISSUE TITLE
NekoString union opti

### ISSUE THREAD

**Issue by StephenGrosjean** [EliasFarhan/NekoEngine#59]
J'aimerais savoir comment es-ce que je doit utiliser le "union" avec les strings, j'ai compris ce qu'il faisait mais je n'arrive pas à l'implémenter.

```cpp
class NekoString
{
    char* buffer_ = nullptr;
    size_t length_ = 0;
    Allocator& allocator_;
```

**Comment by EliasFarhan** [comment]
Bah t'as toujours besoin de la length, par contre, plutôt de d'avoir un
buffer et un allocator, tu peux mettre directement dans un tableau sur la
stack de la même taille comme ici https://godbolt.org/z/SxCo2e
