### ISSUE TITLE
erreur test crash 

### ISSUE THREAD

**Issue by AdamNaji** [EliasFarhan/NekoEngine#60]
lorsque que j'essaye de lancer un de mes test , ça crash. même si je mets un break-point au debut de mon test ça crash quand même 

voici l'erreur

![12125](https://user-images.githubusercontent.com/43807452/80376690-7e170380-889a-11ea-9a94-3c4d40172a9e.PNG)

**Comment by EliasFarhan** [comment]
Là ca veut dire que tu dépasses la taille de ton std::vector (il faut quand
même lire le message d'erreur... "Expression: vector subscript out of
range" est plutôt claire)

Le truc, c'est que je peux pas t'aider plus que ca, parce que je vois pas
ton code... (Ni de ton test, ni de ta queue)

**Comment by AdamNaji** [comment]
![image](https://user-images.githubusercontent.com/43807452/80378073-66d91580-889c-11ea-9fd6-06f9185db342.png)

voici le code de mon test , et meme en ayant un breakpoint a cette endroit la il n'est pas detecter
et ca crash

**Comment by EliasFarhan** [comment]
T'es en Debug sur MSVC? Le breakpoint va prendre une ligne de code, pas une
ligne dans le vide.
Quand t'as l'erreur, fais retry (ce qui est marqué dans le message
d'erreur, vu que t'as MSVC en français, ca se traduit en "Recommencer")
pour voir où tu dépasses la taille de ton std::vector.

Est-ce que je dois vraiment refaire un cours de debug du module GPR4100?
