### ISSUE TITLE
Comment tester l'exactitude des opérations sur les transforms? [Oleg]

### ISSUE THREAD

**Issue by LoshkinOleg** [EliasFarhan/NekoEngine#7]
Je pense avoir implementé toutes les opérations sur les transforms à part les rotations en utilisant les quaternions.

Le truc c'est que j'ai aucune idée de savoir si ce que j'ai fait est juste vu qu'on peux pas voir directement les valeurs de position, rotation, etc, en regardant une matrice 4x4 et je ne crois pas qu'il y aie de système dans l'engine qui utilise les opérations de transforms pour voir leur effet?

Qqn sait comment je peux tester si ce que j'ai fait est juste?

**Comment by EliasFarhan** [comment]
Pour une matrice de translation, si tu multiplies la matrice avec une
position Vec4f, le résulat est la position translaté. Même chose pour la
matrice de scale et rotation.

Il y a aussi l'exemple 03_hello_transform dans comp_graph qui applique tes
fonctions sur un plan et un cube.

**Comment by LoshkinOleg** [comment]
@Elias Ouaip, mais comment je lance 03_hello_transform sous Clion Ubuntu?... Il fait pas partie des Configurations et quand j'ouvre son main.cpp, Clion dit que le fichier n'appartient à aucun projet...

J'ai fouillé un peu dans les settings du projet mais je comprends pas vraiment comment en faire une Configuration que je peux builder et lançer?...

Et pour example d'une translation d'une matrice 4x4:

1 0 0 0
0 1 0 0
0 0 1 0
0 0 0 1

Multiplié par (1, 1, 1) ça donne bien?

1 0 0 1
0 1 0 1
0 0 1 1
0 0 0 1

Ou j'ai mal compris qqch?

Edit: Est-ce que c'est normal que ça me sors ça lors de la generation du projet par CMake?:
```
Main project path: /home/user/Desktop/NekoEngine/main//city_builder and name: city_builder
Main project path: /home/user/Desktop/NekoEngine/main//comp_graph and name: comp_graph
Main project path: /home/user/Desktop/NekoEngine/main//neko_editor3d and name: neko_editor3d
Main project path: /home/user/Desktop/NekoEngine/main//net_prediction_simulation and name: net_prediction_simulation
Main project path: /home/user/Desktop/NekoEngine/main//pathfinder and name: pathfinder
```

C'est normal qu'il y aie 2 forward slash avant le nom du ficher?

**Comment by EliasFarhan** [comment]
Il faut ouvrir le cmake-build-release avec cmake-gui (cmake-qt-gui ou
cmake-curses gui avec apt) et cocher comp_graph.
Sinon pour ta question pour la translation, c'est effectivement ça si ta
translation est bien de (1,1,1), en gros, un translation (X,Y,Z):
1 0 0 X
0 1 0 Y
0 0 1 Z
0 0 0 1
Ca veut dire qu'il faut multiplier la matrice transform avec cette matrice
de translation.

**Comment by LoshkinOleg** [comment]
Parfait, ça marche merci!

SOLUTION pour ceux qui rencontreraient le meme soucis:
- Download CMake si c'est pas déja fait
- Ouvrez le GUI de CMake
- Selectionnez le dossier NekoEngine pour le field source
- Selectionnez le dossier NekoEngine/cmake-build-debug ou NekoEngine/cmake-build-release pour le dossier build selon la version que vous voulez.
- Cochez la case pour le target que vous voulez générer (ex: comp_graph)
- Clickez sur Generate et quittez le GUI
- Revenez dans CLion et relançez la génération du projet dans l'onglet CMake de Clion (l'icone de deux flèches qui tournent)

**Comment by EliasFarhan** [comment]
Tu peux ajouter cette marche à suivre dans la page wiki pour Ubuntu (si c'est pas déjà fait).
