### ISSUE TITLE
Fonctions à implémenter dans vector.h?

### ISSUE THREAD

**Issue by CanasSimon** [EliasFarhan/NekoEngine#8]
Quelles sont les fonctions qu'il faut impérativement implémenter pour l'instant? Car AngleBetween(), Dot() et Lerp() (pour Vec2) sont déjà implémentés.

Aussi, serait-il utile d'ajouter d'ajouter d'autres formules comme:
- Le cross product
- La normal
- La projection
- La reflection

**Comment by EliasFarhan** [comment]
Exactement, tu peux t'inspirer des Vector2, 3 et 4 d'Unity pour les
fonctions à implémenter et toutes les valeurs up, down, right, etc...

Par contre je comprends pas ce que tu veux faire avec la normale?

**Comment by CanasSimon** [comment]
La normale est utilisé dans plusieurs formules (dont celle de la reflection) donc je me disais que ça pouvais être utile?

**Comment by EliasFarhan** [comment]
Oui, mais c'est pas une fonction particulière, c'est juste un vecteur
unitaire (normalisé), non?

**Comment by CanasSimon** [comment]
C'est pas le vecteur perpendiculaire à l'autre?

**Comment by EliasFarhan** [comment]
En géométrie, en 2d, une droite (pas un vecteur) peut avoir une normale, en 3 un plan/une sphère peut avoir une normale. Normalement Adam (@AdamNaji) et Luca (@FloreauLuca) bossent sur les shapes et donc ont implémentés leurs normales.

Si tu veux avoir une fonction qui génère un vecteur perpendiculaire, le problème que tu auras c'est que t'as pleins de vecteurs perpendiculaires à un vecteur.

**Comment by CanasSimon** [comment]
Ok; je penses voir
