### ISSUE TITLE
Rotation de matrice 4x4 [Oleg]

### ISSUE THREAD

**Issue by LoshkinOleg** [EliasFarhan/NekoEngine#9]
Je n'arrive pas à implémenter les rotations de matrices 4x4 et je n'arrive pas à comprendre l'origine de mon erreur. J'ai essayé d'implémenter la formule trouvée ici: https://en.wikipedia.org/wiki/Rotation_matrix dans "Axis and angle"

Mon code:

    Transform3d output = transform;
    axis = axis / axis.GetMagnitude();
    const float x = axis[0];
    const float y = axis[1];
    const float z = axis[2];
    const float c = cosf(angle);
    const float s = sinf(angle);
    const float t = 1.0f - c;

    output[0][0] *= t*x*x + c;
    output[0][1] *= t*x*y + s*z;
    output[0][2] *= t*x*z - s*y;

    output[1][0] *= t*x*y - s*z;
    output[1][1] *= t*y*y + c;
    output[1][2] *= t*y*z + s*x;

    output[2][0] *= t*x*z + s*y;
    output[2][1] *= t*y*z - s*x;
    output[2][2] *= t*z*z + c;

    return output;

Le resultat est un scaling sur x et y (z je sais pas).

J'ai adapté le code du PokEngine pour test et ça marche effectivement:

    const float angleCos = cos(angle);
    const float angleSin = sin(angle);

    Vec3 axisNorma = axis / axis.GetMagnitude();
    Vec3 temp = axisNorma * (1.0f - angleCos);

    Mat4f rotate = Mat4f();

    rotate[0][0] = angleCos + temp.x * axisNorma.x;
    rotate[0][1] = temp.x * axisNorma.y + angleSin * axisNorma.z;
    rotate[0][2] = temp.x * axisNorma.z - angleSin * axisNorma.y;

    rotate[1][0] = temp.y * axisNorma.x - angleSin * axisNorma.z;
    rotate[1][1] = angleCos + temp.y * axisNorma.y;
    rotate[1][2] = temp.y * axisNorma.z + angleSin * axisNorma.x;

    rotate[2][0] = temp.z * axisNorma.x + angleSin * axisNorma.y;
    rotate[2][1] = temp.z * axisNorma.y - angleSin * axisNorma.x;
    rotate[2][2] = angleCos + temp.z * axisNorma.z;

    Mat4f result = Mat4f();
    result[0] = transform[0] * rotate[0][0] + transform[1] * rotate[0][1] +
                transform[2] * rotate[0][2];
    result[1] = transform[0] * rotate[1][0] + transform[1] * rotate[1][1] +
                transform[2] * rotate[1][2];
    result[2] = transform[0] * rotate[2][0] + transform[1] * rotate[2][1] +
                transform[2] * rotate[2][2];
    result[3] = transform[3];

    return result;

J'ai du mal à comprendre la différence fondamentale entre les 2 approches. En soit ça marche mais c'est juste pcq j'ai copy/paste comme un porc :/

**Comment by EliasFarhan** [comment]
Premier truc, utilise cosf et sinf pour des floats ;)

Deuxième, il faut que tu crées une matrice et que tu la multiplies avec le transform en argument, c'est ce que fais le deuxième exemple (d'ailleurs translate et scale doit faire la même chose).

**Comment by LoshkinOleg** [comment]
J'ai besoin d'aide pour l'ordre des opérations des transforms...
J'ai mis les trasnforms dans leur propre header dans mathematics et j'ai passé la journée à essayer de mieux comprendre les matrices.

Si j'ai bien compris donc, dans notre engine, vu qu'on utilise openGL, les matrices sont column major, donc chaque Vec3f dans une Mat4f représente une colonne. Donc on applique les formules de matrice trouvées sur Wikipedia par example telles quelles, pas des versions transposées de ces formules.

Vu que c'est openGL, pour les multiplications entre 2 matrices du genre Mat4f * Mat4f il faut faire ValeurARetourner * MatriceDeTransformation.

Pour les multiplications à plus de 2 matrices, il faut les écrire dans l'ordre inverse qu'on les veux appléquées, donc si on veux: translate => rotate => scale, on doit faire newMat = oldMat * scale * rotate * translate.

Le bon ordre des transformations pour openGL est: rotate => scale => move   donc l'ordre inverse si on veux appliquer ces transformations dans les multiplications.

Mon problème est que j'ai tout de meme la translation qui ne marche pas.
Voici le code de l'update du comp_graph:

```
transform_ = Mat4f::Identity;
transform_ =
            Mat4f::Translate(transform_, position_) *
            Mat4f::Scale(transform_, scale_) *
            Mat4f::Rotate(transform_, degree_t(angle_), Vec3f(0.0f, 0.0f, 1.0f));
```

Voici le code qui applique les transformations:
```
inline Transform3d Transform3d::Translate(const Transform3d& transform, const Vec3f translation)
{
    return transform * TranslationMatrixFrom(translation);
}

template<>
inline Transform3d Transform3d::Scale(const Transform3d& transform, const Vec3f scale)
{
    return transform * ScalingMatrixFrom(scale);
}

template<>
inline Transform3d Transform3d::Rotate(const Transform3d& transform, const degree_t angle, const Vec3f axis)
{
    return transform * RotationMatrixFrom(angle, axis);
}
```

Et voici le code de ces fonctions:
```
inline Mat4f const Transform3d::TranslationMatrixFrom(const Vec3f translation)
{
    return Mat4f(
            std::array<Vec4f, 4>
                    {
                            Vec4f(1.0f, 0, 0, translation[0]),
                            Vec4f(0, 1.0f, 0, translation[1]),
                            Vec4f(0, 0, 1.0f, translation[2]),
                            Vec4f(0, 0, 0, 1)});
}

template<>
inline Mat4f const Transform3d::ScalingMatrixFrom(const Vec3f scale)
{
    return Mat4f(
            std::array<Vec4f, 4>
                    {
                            Vec4f(scale[0], 0, 0, 0),
                            Vec4f(0, scale[1], 0, 0),
                            Vec4f(0, 0, scale[2], 0),
                            Vec4f(0, 0, 0, 1)});
}

template<>
inline Mat4f const Transform3d::RotationMatrixFrom(const degree_t angle, const Vec3f axis)
{
    const float angleAsFloat = static_cast<degree_t>(angle).to<float>();
    const Vec3f normalizedAxis = axis / axis.GetMagnitude();

    const float x = axis[0];
    const float y = axis[1];
    const float z = axis[2];
    const float c = std::cos(angleAsFloat);
    const float s = std::sin(angleAsFloat);
    const float t = 1.0f - c;
    const float txx = t * x * x;
    const float tyy = t * y * y;
    const float tzz = t * z * z;
    const float txy = t * x * y;
    const float txz = t * x * z;
    const float tyz = t * y * z;
    const float sx = s * x;
    const float sy = s * y;
    const float sz = s * z;

    return Mat4f(
            std::array<Vec4f, 4>
                    {
                            Vec4f(txx + c, txy - sz, txz + sy, 0),
                            Vec4f(txy + sz, tyy + c, tyz - sx, 0),
                            Vec4f(txz - sy, tyz + sx, tzz + c, 0),
                            Vec4f(0, 0, 0, 1)});
}
```

Je voudrais bien passer à l'optimisation, mais ce serait pas mal de pouvoir faire marcher ces transformations d'abord...

Le problème actuel est que la translation ne marche pas: la modification des coordonnées x, y et z via l'éditeur dans le comp_graph donne un effet de scaling proportionnel sur tous les axes sur le rectangle...

Je ne sais pas vraiment quoi d'autre essayer. Help

**Comment by EliasFarhan** [comment]
Vu que t'as fait les fonctions pour générer les matrices de transformation, ce serait mieux de faire:
```
transform_ = Mat4f::Identity;
transform_ =
            Mat4f::TranslateMatrixFrom(position_) *
            Mat4f::ScaleMatrixFrom(scale_) *
            Mat4f::RotationMatrixFrom(degree_t(angle_), Vec3f(0.0f, 0.0f, 1.0f)) *
            transform_;
```
Sinon tu dois faire quelque chose du genre (ou l'inverse):
```
transform_ = Mat4f::Identity;
transform_ =
            Mat4f::Translate(Mat4f::Scale(Mat4f::Rotate(transform_, degree_t(angle_), Vec3f(0.0f, 0.0f, 1.0f)), scale_) , position_);
```

**Comment by LoshkinOleg** [comment]
Mystère résolu: MultiplyIntrensics() est bugguée, faut utiliser MultiplyNaive()
